### ISSUE TITLE
ERR : extra arguments to `rustc` can only be passed to one target

### ISSUE THREAD

**Issue by rusty-easy** [dodorare/crossbow#86]
## Problem

I followed these tutorials : 
- https://github.com/dodorare/crossbow/blob/main/docs/install-windows-android.md
- https://github.com/dodorare/crossbow/wiki/Hello-World!

But after launching an android emulator and running this command, I get this error :
```
$ crossbundle run android
Starting build process: project
Generating: AndroidManifest.xml
Compiling: lib
Compiling for architecture: aarch64-linux-android
error: Crossbundle Tools error
caused by: Anyhow error
caused by: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing, e.g., `--lib` or `--bin NAME` to specify a single target
```
I would like to know where is the problem....

## Versions

Operating system : ``Windows 10``

NDK version : ``24.0.8215888``

```
$ rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

```
$ crossbundle --version
crossbundle 0.1.3
```

**Comment by enfipy** [comment]
@rusty-easy Hey! Thanks for the issue. Our Wiki in Github was outdated, I disabled it. Please see the hello world example from our [docs](https://github.com/dodorare/crossbow/blob/main/docs/main-hello-world.md). It should work with the latest version of crossbundle (if installed through `cargo install --git=https://github.com/dodorare/crossbow crossbundle`).

**Comment by rusty-easy** [comment]
I uninstalled crossbundle : 
```
$ cargo uninstall crossbundle 
```

Then, I reinstalled it: 
```
$ cargo install --git=https://github.com/dodorare/crossbow crossbundle
```

But when I create a new project with this command :  
```
$ crossbundle new project-name
```

I get a 2018 edition of a crossbundle project :
````toml
[package]
name = "project-name"
version = "0.1.0"
authors = ["User"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
creator = "0.4.1"

[package.metadata]
icon = "ic_launcher"
android_res = "res/android"
apple_res = "res/apple"
````

I don't know why ....
